// ---------------------------------------------------------------------------
// detectDependencies
// Scans Sandpack file map and returns { packageName: "latest" } for every
// third-party npm dependency found via import/require statements.
// ---------------------------------------------------------------------------

// Valid npm package name pattern (supports normal packages and @scoped/packages).
const NPM_PACKAGE_REGEX =
  /^(?:@[a-z0-9-~][a-z0-9-._~]*\/)?[a-z0-9-~][a-z0-9-._~]*$/;

// Strips JS/TS block and line comments before import scanning.
const stripComments = (code) => {
  return code
    .replace(/\/\*[\s\S]*?\*\//g, "")
    .replace(/(^|[^:])\/\/.*$/gm, "$1");
};

export function detectDependencies(files) {
  const deps = {};
  if (!files || typeof files !== "object") return deps;

  const filePaths = Object.keys(files);

  for (const path of filePaths) {
    if (!path.match(/\.(js|jsx|ts|tsx)$/)) continue;

    const file = files[path];
    const raw =
      typeof file === "string"
        ? file
        : file?.code ?? file?.content ?? "";

    if (!raw) continue;

    const code = stripComments(raw);

    // Match: import ... from 'pkg'  |  require('pkg')
    const importRegex =
      /(?:import\s+(?:[\w*{},\s]+\s+from\s+)?|require\s*\(\s*)['"]([^'"]+)['"]/g;

    let match;
    while ((match = importRegex.exec(code)) !== null) {
      const pkg = match[1];

      // Skip relative / absolute paths
      if (pkg.startsWith(".") || pkg.startsWith("/")) continue;

      // Extract the package root (e.g. "react-dom/client" → "react-dom")
      const pkgRoot = pkg.startsWith("@")
        ? pkg.split("/").slice(0, 2).join("/")
        : pkg.split("/")[0];

      if (NPM_PACKAGE_REGEX.test(pkgRoot)) {
        deps[pkgRoot] = "latest";
      }
    }
  }

  return deps;
}

// ---------------------------------------------------------------------------
// sanitizeFilesForSandpack
// Normalises the file map into the { code: string } shape Sandpack expects.
// Files are expected to be clean (generated by your Python backend) so we
// only do structural normalisation here, not content scrubbing.
// ---------------------------------------------------------------------------
export function sanitizeFilesForSandpack(files) {
  if (!files || typeof files !== "object") return {};

  const result = {};

  for (const [path, file] of Object.entries(files)) {
    if (typeof file === "string") {
      result[path] = { code: file };
    } else if (file && typeof file === "object") {
      result[path] = {
        ...file,
        code: file.code ?? file.content ?? "",
      };
    } else {
      result[path] = { code: "" };
    }
  }

  return result;
}